# Generated by Django 4.2.9 on 2026-01-26 05:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=50, verbose_name='Nacionalidad')),
                ('foto', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto de Perfil')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Profesional')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EC', verbose_name='Teléfono')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('portafolio_web', models.URLField(blank=True, verbose_name='Portafolio Web')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia/Estado')),
                ('pais', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('titulo_profesional', models.CharField(max_length=150, verbose_name='Título Profesional')),
                ('nivel_experiencia', models.CharField(choices=[('junior', 'Junior (0-2 años)'), ('mid', 'Mid-Level (3-5 años)'), ('senior', 'Senior (6-10 años)'), ('lead', 'Lead/Principal (10+ años)')], default='mid', max_length=10)),
                ('anos_experiencia', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('resumen_profesional', models.TextField(max_length=500, verbose_name='Resumen Profesional')),
                ('objetivo_profesional', models.TextField(blank=True, max_length=300, verbose_name='Objetivo Profesional')),
                ('cv_publico', models.BooleanField(default=False, verbose_name='CV Público')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Profesional',
                'verbose_name_plural': 'Perfiles Profesionales',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('relacion', models.CharField(help_text='Ej: Ex-supervisor directo, Colega de equipo', max_length=200, verbose_name='Relación Profesional')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EC', verbose_name='Teléfono')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('testimonio', models.TextField(blank=True, max_length=500, verbose_name='Testimonio/Recomendación')),
                ('mostrar_contacto', models.BooleanField(default=False, help_text='Si está desactivado, solo se mostrará el nombre y cargo', verbose_name='Mostrar Información de Contacto')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='curriculum.perfilprofesional')),
            ],
            options={
                'verbose_name': 'Referencia Profesional',
                'verbose_name_plural': 'Referencias Profesionales',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion_corta', models.CharField(max_length=200, verbose_name='Descripción Corta')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción Detallada')),
                ('estado', models.CharField(choices=[('en_desarrollo', 'En Desarrollo'), ('completado', 'Completado'), ('mantenimiento', 'En Mantenimiento'), ('archivado', 'Archivado')], default='completado', max_length=20)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('rol', models.CharField(help_text='Ej: Desarrollador Full Stack', max_length=100, verbose_name='Tu Rol')),
                ('tecnologias', models.CharField(max_length=500, verbose_name='Tecnologías Utilizadas')),
                ('url_demo', models.URLField(blank=True, verbose_name='URL Demo/Sitio')),
                ('url_repositorio', models.URLField(blank=True, verbose_name='Repositorio (GitHub/GitLab)')),
                ('imagen', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Imagen del Proyecto')),
                ('destacado', models.BooleanField(default=False, verbose_name='Proyecto Destacado')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='curriculum.perfilprofesional')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-destacado', '-fecha_inicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Habilidad')),
                ('tipo', models.CharField(choices=[('tecnica', 'Habilidad Técnica'), ('blanda', 'Habilidad Blanda'), ('idioma', 'Idioma'), ('herramienta', 'Herramienta/Software')], default='tecnica', max_length=15)),
                ('nivel', models.PositiveIntegerField(default=50, help_text='0 = Básico, 50 = Intermedio, 100 = Experto', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de Dominio (%)')),
                ('anos_experiencia', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripción')),
                ('certificado', models.FileField(blank=True, upload_to='certificates/skills/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Certificado')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('destacada', models.BooleanField(default=False, verbose_name='Habilidad Destacada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='curriculum.perfilprofesional')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['-destacada', 'tipo', '-nivel', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('bachillerato', 'Bachillerato'), ('tecnico', 'Técnico/Tecnólogo'), ('pregrado', 'Pregrado/Licenciatura'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=20, verbose_name='Nivel de Educación')),
                ('titulo_obtenido', models.CharField(max_length=200, verbose_name='Título Obtenido')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución Educativa')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(choices=[('cursando', 'Cursando'), ('completado', 'Completado'), ('incompleto', 'Incompleto')], default='completado', max_length=15)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Promedio/GPA')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('certificado', models.FileField(blank=True, upload_to='certificates/education/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificado (PDF)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacion_academica', to='curriculum.perfilprofesional')),
            ],
            options={
                'verbose_name': 'Formación Académica',
                'verbose_name_plural': 'Formación Académica',
                'ordering': ['-fecha_inicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo/Posición')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('tipo_empleo', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance'), ('contrato', 'Contrato'), ('pasantia', 'Pasantía')], default='tiempo_completo', max_length=20)),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('trabajo_actual', models.BooleanField(default=False, verbose_name='Trabajo Actual')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción de Responsabilidades')),
                ('logros', models.TextField(blank=True, max_length=1000, verbose_name='Logros Principales')),
                ('tecnologias_usadas', models.CharField(blank=True, max_length=500, verbose_name='Tecnologías Utilizadas')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='curriculum.perfilprofesional')),
            ],
            options={
                'verbose_name': 'Experiencia Profesional',
                'verbose_name_plural': 'Experiencias Profesionales',
                'ordering': ['-fecha_inicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Certificación/Curso')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución/Plataforma')),
                ('fecha_obtencion', models.DateField(verbose_name='Fecha de Obtención')),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('codigo_credencial', models.CharField(blank=True, max_length=100, verbose_name='Código de Credencial')),
                ('url_verificacion', models.URLField(blank=True, verbose_name='URL de Verificación')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('certificado', models.FileField(blank=True, upload_to='certificates/certifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Certificado')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='curriculum.perfilprofesional')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['-fecha_obtencion', 'orden'],
            },
        ),
    ]
